### PR TITLE
Rename README file with proper extension to get cute github rendering

### PR DESCRIPTION
**Pull request by skeuomorf**

### CODE REVIEW

**Comment by mity** [comment]
Thanks. But if you rename the file to enable github markdown rendering, you should also adapt the contents of the file to follow the expected syntax. See how the title, and various code (C, shell) snippets in it are now rendered...

**Comment by skeuomorf** [comment]
@mity Oops, my mistake, will fix :)

**Comment by skeuomorf** [comment]
@mity Should be better now :)

**Comment by mity** [comment]
Thanks.

**Comment by skeuomorf** [comment]
Cheers, thanks for merging and for working on CUTest.

**Pull request merged**
